-- SPM元素交互记录表
CREATE TABLE IF NOT EXISTS element_interactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL COMMENT '用户ID',
    session_id VARCHAR(100) COMMENT '会话ID',
    page_url TEXT NOT NULL COMMENT '页面URL',
    spm_id VARCHAR(200) NOT NULL COMMENT 'SPM标识',
    element_tag VARCHAR(50) COMMENT '元素标签',
    element_class VARCHAR(500) COMMENT '元素类名',
    element_id VARCHAR(100) COMMENT '元素ID',
    element_text VARCHAR(100) COMMENT '元素文本',
    trigger_type ENUM('click', 'view', 'custom') DEFAULT 'click' COMMENT '触发类型',
    position_x INT COMMENT '元素X坐标',
    position_y INT COMMENT '元素Y坐标',
    element_width INT COMMENT '元素宽度',
    element_height INT COMMENT '元素高度',
    timestamp BIGINT NOT NULL COMMENT '交互时间戳',
    ip_address VARCHAR(45) COMMENT 'IP地址',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_session_id (session_id),
    INDEX idx_spm_id (spm_id),
    INDEX idx_trigger_type (trigger_type),
    INDEX idx_timestamp (timestamp),
    INDEX idx_page_url (page_url(255)),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB COMMENT='SPM元素交互记录表';